### ISSUE TITLE
 is Semantic search example similar to project GPTcache

### ISSUE THREAD

**Issue by oneanime** [ThomasVitale/llm-apps-java-spring-ai#1]

**Comment by ThomasVitale** [comment]
The underlying techniques are the same. GPTcache provides a cache between an application and an LLM service. It uses the same principles of the semantic search example in this repo in order to generate embeddings for every user request to the model and store it in a vector database. If a new request is sent, then GPTcache performs a semantic search on the vector database to check if a similar request has been sent before. If it finds a result, then it will return the cached response instead of calling the LLM service again.

Does that answer your question?

**Comment by ThomasVitale** [comment]
Closing this issue for now. Feel free to leave a comment here or open a new issue, should you have more questions about this topic.
